// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async meta() : Promise<Result<InitData, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("meta") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async init() : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWindow(theme: Theme, windowEffect: WindowEffect) : Promise<Result<[boolean, string | null], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_window", { theme, windowEffect }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configWrite(settings: Partial<{ [key in string]: JsonValue }>) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_write", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openCache(key: CacheKey) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_cache", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSize(key: CacheKey, event: TAURI_CHANNEL<number>) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_size", { key, event }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cleanCache(key: CacheKey) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clean_cache", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dbImport(input: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_import", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dbExport(output: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_export", { output }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportData(output: string, data: JsonValue) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_data", { output, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopLogin() : Promise<void> {
    await TAURI_INVOKE("stop_login");
},
async exit() : Promise<Result<number, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("exit") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async smsLogin(cid: number, tel: string, code: string, captchaKey: string) : Promise<Result<number, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sms_login", { cid, tel, code, captchaKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pwdLogin(username: string, encodedPwd: string, token: string, challenge: string, validate: string, seccode: string) : Promise<Result<number, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pwd_login", { username, encodedPwd, token, challenge, validate, seccode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async switchCookie(switchCode: string) : Promise<Result<number, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("switch_cookie", { switchCode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanLogin(qrcodeKey: string, event: TAURI_CHANNEL<number>) : Promise<Result<number, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_login", { qrcodeKey, event }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshCookie(refreshCsrf: string) : Promise<Result<number, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_cookie", { refreshCsrf }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ctrlEvent(event: CtrlEvent, sid: string | null, id: string | null) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ctrl_event", { event, sid, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openFolder(sid: string | null, id: string | null) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_folder", { sid, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async submitTask(id: string, value: TaskView) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("submit_task", { id, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async planScheduler(sid: string, folder: string) : Promise<Result<SchedulerView, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plan_scheduler", { sid, folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async processScheduler(sid: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("process_scheduler", { sid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 扫描缓存目录（仅扫描，不导入）
 */
async scanCacheDirectory(path: string) : Promise<Result<ScanResult, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_cache_directory", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 导入缓存目录
 */
async importCacheDirectory(path: string, options: ImportOptions) : Promise<Result<string, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_cache_directory", { path, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取导入进度（使用 Channel 事件流）
 */
async getImportProgress(importId: string, event: TAURI_CHANNEL<ImportProgress>) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_import_progress", { importId, event }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 取消导入操作
 */
async cancelImport(importId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_import", { importId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取缓存列表（自动清理不存在的文件）
 */
async getCacheList() : Promise<Result<CacheRecord[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cache_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 根据状态获取缓存列表（自动清理不存在的文件）
 */
async getCacheListByStatus(status: string) : Promise<Result<CacheRecord[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cache_list_by_status", { status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 清理无效的缓存记录（文件不存在的记录）
 */
async cleanupInvalidCacheRecords() : Promise<Result<number, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_invalid_cache_records") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 增量扫描缓存根目录，检测新增或删除的视频
 */
async incrementalScanCacheRoot() : Promise<Result<IncrementalScanResult, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("incremental_scan_cache_root") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除缓存项（同时删除文件和数据库记录）
 */
async deleteCacheItem(id: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_cache_item", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 打开缓存文件夹
 */
async openCacheFolder(cachePath: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_cache_folder", { cachePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 检查本地封面文件
 */
async checkLocalCover(cachePath: string) : Promise<Result<string | null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_local_cover", { cachePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取缓存统计信息
 */
async getCacheStats() : Promise<Result<CacheStats, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cache_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取完整的缓存统计信息（包含组统计）
 */
async getCacheStatistics() : Promise<Result<CacheStatistics, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cache_statistics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取缓存显示项列表（组和单个视频的混合）
 */
async getCacheDisplayItems() : Promise<Result<DisplayItem[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cache_display_items") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取缓存显示项列表（带分页支持）
 */
async getCacheDisplayItemsPaginated(page: number, pageSize: number, sortBy: string | null, sortOrder: string | null, filters: CacheFilterOptions | null) : Promise<Result<PaginatedDisplayItems, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cache_display_items_paginated", { page, pageSize, sortBy, sortOrder, filters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 切换组的展开状态
 */
async toggleGroupExpansion(groupId: string) : Promise<Result<boolean, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_group_expansion", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 设置组的展开状态
 */
async setGroupExpansion(groupId: string, isExpanded: boolean) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_group_expansion", { groupId, isExpanded }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取组统计信息
 */
async getGroupStatistics() : Promise<Result<GroupStatistics, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_group_statistics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取所有组的展开/折叠状态
 */
async getGroupStates() : Promise<Result<CacheGroupState[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_group_states") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 根据组ID获取组内视频
 */
async getVideosByGroupId(groupId: string) : Promise<Result<CacheRecord[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_videos_by_group_id", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除整个组
 */
async deleteGroup(groupId: string) : Promise<Result<number, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_group", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 清理孤立的组状态
 */
async cleanupOrphanedGroupStates() : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_orphaned_group_states") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 批量删除缓存项（支持组和单个视频）
 */
async batchDeleteCacheItems(itemIds: string[], itemTypes: string[]) : Promise<Result<BatchOperationResult, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_delete_cache_items", { itemIds, itemTypes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 批量导出缓存项
 */
async batchExportCacheItems(itemIds: string[], itemTypes: string[], exportPath: string) : Promise<Result<BatchOperationResult, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_export_cache_items", { itemIds, itemTypes, exportPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 发现可用的传输目标（本地文件夹和移动设备）
 */
async discoverTransferTargets() : Promise<Result<TransferTarget[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_transfer_targets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 验证传输目标的有效性
 */
async validateTransferTarget(target: TransferTarget) : Promise<Result<boolean, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_transfer_target", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 检查目标位置的可用空间
 */
async checkAvailableSpace(targetPath: string, requiredSize: number) : Promise<Result<boolean, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_available_space", { targetPath, requiredSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 打开文件夹选择对话框
 */
async selectFolder() : Promise<Result<string | null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("select_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 开始文件传输
 */
async startTransfer(request: TransferRequest) : Promise<Result<string, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_transfer", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 开始缓存根目录迁移
 */
async startRootMigration(request: RootMigrationRequest) : Promise<Result<string, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_root_migration", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 暂停传输任务
 */
async pauseTransfer(taskId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_transfer", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 恢复传输任务
 */
async resumeTransfer(taskId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_transfer", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 取消传输任务
 */
async cancelTransfer(taskId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_transfer", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取传输进度
 */
async getTransferProgress(taskId: string) : Promise<Result<TransferProgress | null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transfer_progress", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取所有活跃的传输任务
 */
async getActiveTransfers() : Promise<Result<TransferTask[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_transfers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取队列中的传输任务
 */
async getQueuedTransfers() : Promise<Result<TransferTask[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_queued_transfers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取已完成的传输任务
 */
async getCompletedTransfers() : Promise<Result<TransferTask[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_completed_transfers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 清空已完成的传输任务
 */
async clearCompletedTransfers() : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_completed_transfers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取当前缓存根目录
 */
async getCurrentCacheRoot() : Promise<Result<string, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_cache_root") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 设置缓存根目录
 */
async setCacheRoot(path: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_cache_root", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取设备列表
 */
async getDeviceList() : Promise<Result<DeviceInfo[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_device_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 监听设备变化（使用 Channel 事件流）
 */
async listenDeviceChanges(event: TAURI_CHANNEL<DeviceInfo[]>) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("listen_device_changes", { event }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 监听传输进度更新（使用 Channel 事件流）
 */
async listenTransferProgress(taskId: string, event: TAURI_CHANNEL<TransferProgress>) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("listen_transfer_progress", { taskId, event }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
headersData: HeadersData,
processError: ProcessError,
queueEvent: QueueEvent
}>({
headersData: "headers-data",
processError: "process-error",
queueEvent: "queue-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AnyInt = number
/**
 * 批量操作结果
 */
export type BatchOperationResult = { success_count: number; deleted_videos: number; deleted_groups: number; error_count: number; errors: string[] }
/**
 * 缓存筛选选项
 */
export type CacheFilterOptions = { search_query: string | null; filter_status: string | null; filter_uploader: string | null; min_size: number | null; max_size: number | null; min_duration: number | null; max_duration: number | null; display_type: string | null; group_id: string | null }
/**
 * 缓存视频组
 */
export type CacheGroup = { group_id: string; title: string; cover_url: string; uname: string; video_count: number; total_duration: number; total_file_size: number; latest_download_time: number; videos: CacheRecord[]; is_expanded: boolean }
export type CacheGroupState = { group_id: string; is_expanded: boolean; created_at: number; updated_at: number }
export type CacheKey = "log" | "temp" | "webview" | "database"
export type CacheRecord = { id: string; bvid: string; aid: number; cid: number; title: string; uname: string; cover_url: string; duration: number; file_size: number; cache_path: string; download_time: number; import_time: number; status: string; source: string; group_id: string | null; group_title: string | null; p: number }
/**
 * 完整的缓存统计信息
 */
export type CacheStatistics = { total_count: number; available_count: number; unavailable_count: number; incomplete_count: number; total_size: number; average_size: number; total_duration: number; group_count: number; single_video_count: number; average_videos_per_group: number }
/**
 * 缓存统计信息
 */
export type CacheStats = { total_count: number; total_size: number; available_count: number }
/**
 * 文件名冲突处理策略
 */
export type ConflictStrategy = 
/**
 * 跳过
 */
"Skip" | 
/**
 * 覆盖
 */
"Overwrite" | 
/**
 * 重命名（添加数字后缀）
 */
"Rename" | 
/**
 * 询问用户
 */
"Ask"
/**
 * 设备连接状态
 */
export type ConnectionStatus = 
/**
 * 已连接
 */
"Connected" | 
/**
 * 已断开
 */
"Disconnected"
export type CtrlEvent = "pause" | "resume" | "cancel" | "retry"
/**
 * 设备信息
 */
export type DeviceInfo = { 
/**
 * 设备唯一标识符
 */
id: string; 
/**
 * 设备名称
 */
name: string; 
/**
 * 设备类型
 */
device_type: DeviceType; 
/**
 * 可用空间（字节）
 */
available_space: number | null; 
/**
 * 总空间（字节）
 */
total_space: number | null; 
/**
 * 连接状态
 */
connection_status: ConnectionStatus }
/**
 * 设备类型
 */
export type DeviceType = 
/**
 * 本地驱动器
 */
"LocalDrive" | 
/**
 * 可移动存储设备（U盘、移动硬盘等）
 */
"RemovableStorage"
/**
 * 显示项枚举（组或单个视频）
 */
export type DisplayItem = { type: "single_video"; video: CacheRecord } | { type: "video_group"; group: CacheGroup }
/**
 * 重复处理策略
 */
export type DuplicateHandlingStrategy = 
/**
 * 跳过重复项
 */
"Skip" | 
/**
 * 覆盖现有记录
 */
"Overwrite" | 
/**
 * 询问用户（暂不实现，预留）
 */
"Ask"
/**
 * 错误统计信息
 */
export type ErrorStatistics = { total_errors: number; error_by_type: Partial<{ [key in string]: number }>; error_by_severity: Partial<{ [key in string]: number }>; retried_operations: number; skipped_operations: number; aborted_operations: number }
/**
 * 组统计信息
 */
export type GroupStatistics = { total_groups: number; total_videos_in_groups: number; total_single_videos: number; total_duration_in_groups: number; total_size_in_groups: number }
export type HeadersData = { Cookie: string; "User-Agent": string; Referer: string; Origin: string }
/**
 * 导入错误
 */
export type ImportError = { directory_path: string; error_message: string; error_type: string; user_friendly_message: string; suggested_solution: string | null; severity: string; is_retryable: boolean }
/**
 * 导入选项
 */
export type ImportOptions = { 
/**
 * 重复处理策略
 */
duplicate_handling: DuplicateHandlingStrategy; 
/**
 * 是否验证文件完整性
 */
verify_integrity: boolean; 
/**
 * 是否在导入后删除原文件
 */
delete_after_import: boolean; 
/**
 * 是否自动创建播放列表
 */
create_playlist: boolean }
/**
 * 导入进度
 */
export type ImportProgress = { import_id: string; total_directories: number; processed_directories: number; current_directory: string; status: ImportProgressStatus; errors: ImportError[]; error_statistics: ErrorStatistics; estimated_time_remaining: number | null; processing_speed: number }
/**
 * 导入进度状态
 */
export type ImportProgressStatus = "Scanning" | "Parsing" | "Validating" | "Saving" | "Completed" | "Cancelled" | "Error"
/**
 * 增量扫描结果
 */
export type IncrementalScanResult = { scanned_root: string; new_directories_count: number; deleted_directories_count: number; imported_count: number; cleaned_count: number; new_directories: string[]; deleted_directories: string[] }
export type InitData = { version: string; hash: string; config: Settings; tasks: Partial<{ [key in string]: TaskView }>; schedulers: Partial<{ [key in string]: SchedulerView }>; queue: Partial<{ [key in QueueType]: string[] }> }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type MediaItem = { title: string; cover: string; desc: string; duration: number; pubtime: number; type: string; url?: string; aid?: number | null; sid?: number | null; fid?: number | null; cid?: number | null; bvid?: string | null; epid?: number | null; ssid?: number | null; opid?: string | null; rlid?: number | null; index: number }
export type MediaNfo = { showtitle?: string | null; intro?: string | null; tags: string[]; url?: string; stat: JsonValue; thumbs: MediaNfoThumb[]; premiered?: number | null; upper?: MediaNfoUpper | null; credits?: MediaNfoCredits | null }
export type MediaNfoCredit = { role: string | null; name: string | null }
export type MediaNfoCredits = { actors: MediaNfoCredit[]; staff: MediaNfoCredit[] }
export type MediaNfoThumb = { id: string; url: string }
export type MediaNfoUpper = { name: string; mid: number; avatar: string }
/**
 * 分页显示项结果
 */
export type PaginatedDisplayItems = { items: DisplayItem[]; total_count: number; total_pages: number; current_page: number; page_size: number; has_next: boolean; has_prev: boolean }
export type PopupSelect = { res?: number | null; abr?: number | null; enc?: number | null; fmt: StreamFormat; misc: PopupSelectMisc; nfo: PopupSelectNfo; danmaku: PopupSelectDanmaku; thumb: string[]; media: PopupSelectMedia }
export type PopupSelectDanmaku = { live: boolean; history: StringOrFalse }
export type PopupSelectMedia = { video: boolean; audio: boolean; audioVideo: boolean }
export type PopupSelectMisc = { aiSummary: boolean; subtitles: StringOrFalse }
export type PopupSelectNfo = { album: boolean; single: boolean }
export type ProcessError = { name: string; error: string }
export type QueueEvent = { type: "taskUpdated"; id: string; state: TaskState | null; prepare: TaskPrepare | null; cancelled: boolean | null } | { type: "schedulerUpdated"; id: string; state: SchedulerState | null; queue: QueueType | null; list: string[] | null; cancelled: boolean | null } | { type: "progress"; task: string; subtask: string; content: number; chunk: number } | { type: "queue"; name: QueueType; value: string[] } | { type: "request"; task: string; subtask: string | null; action: RequestAction; endpoint: string } | { type: "error"; task: string; subtask: string | null; message: string; code: number | null }
export type QueueType = "backlog" | "pending" | "doing" | "complete"
export type RequestAction = "prepareTask" | "getFilename" | "getNfo" | "getThumbs" | "getDanmaku" | "getSubtitle" | "getAISummary" | "getOpusContent" | "getOpusImages"
/**
 * 缓存根目录迁移请求
 */
export type RootMigrationRequest = { 
/**
 * 目标缓存根目录
 */
target_root: string; 
/**
 * 是否更新数据库
 */
update_database: boolean }
/**
 * 扫描目录信息
 */
export type ScanDirectoryInfo = { path: string; is_valid: boolean; invalid_reason: string | null; preview: ScanPreviewInfo | null }
/**
 * 扫描预览信息
 */
export type ScanPreviewInfo = { title: string; file_size: number; duration: number }
/**
 * 扫描结果
 */
export type ScanResult = { root_path: string; total_directories: number; valid_directories: number; invalid_directories: number; estimated_total_size: number; scan_duration: number; directories: ScanDirectoryInfo[] }
export type SchedulerState = "idle" | "running" | "paused" | "completed" | "failed" | "cancelled"
export type SchedulerView = { sid: string; ts: number; list: string[]; queue: QueueType; state: SchedulerState }
export type Settings = { add_metadata: boolean; auto_check_update: boolean; auto_download: boolean; block_pcdn: boolean; cache_root: string | null; check_update: boolean; clipboard: boolean; convert: SettingsConvert; default: SettingsDefault; down_dir: string; drag_search: boolean; format: SettingsFormat; language: string; max_conc: number; notify: boolean; temp_dir: string; theme: Theme; window_effect: WindowEffect; organize: SettingsOrganize; proxy: SettingsProxy; sidecar: SettingsSidecar; speed_limit: number }
export type SettingsConvert = { danmaku: boolean; mp4: boolean; mp3: boolean }
export type SettingsDefault = { res: number; abr: number; enc: number }
export type SettingsFormat = { series: string; item: string; file: string }
export type SettingsOrganize = { auto_rename: boolean; top_folder: boolean; sub_folder: boolean }
export type SettingsProxy = { address: string; username: string; password: string }
export type SettingsSidecar = { aria2c: string; ffmpeg: string; danmakufactory: string }
export type StreamFormat = "dash" | "mp4" | "flv"
export type StringOrFalse = string | boolean
export type SubTask = { id: string; type: TaskType }
export type SubTaskStatus = { chunk: number; content: number }
export type TaskHotData = { status: Partial<{ [key in string]: SubTaskStatus }>; state: TaskState }
export type TaskMeta = { id: string; ts: number; seq: number; item: MediaItem; type: string }
export type TaskPrepare = { select: PopupSelect; subtasks: SubTask[]; nfo: MediaNfo; folder: string }
export type TaskState = "backlog" | "pending" | "active" | "completed" | "paused" | "failed" | "cancelled"
/**
 * 传输任务状态
 */
export type TaskStatus = 
/**
 * 等待中
 */
"Pending" | 
/**
 * 运行中
 */
"Running" | 
/**
 * 已暂停
 */
"Paused" | 
/**
 * 已完成
 */
"Completed" | 
/**
 * 失败
 */
"Failed" | 
/**
 * 已取消
 */
"Cancelled"
export type TaskType = "opusContent" | "opusImages" | "aiSummary" | "subtitles" | "albumNfo" | "singleNfo" | "liveDanmaku" | "historyDanmaku" | "thumb" | "video" | "audio" | "audioVideo"
export type TaskView = { meta: TaskMeta; prepare: TaskPrepare; hot: TaskHotData }
export type TauriError = { code: AnyInt | null; message: string; stack: string }
export type Theme = 
/**
 * Light theme.
 */
"light" | 
/**
 * Dark theme.
 */
"dark" | 
/**
 * Auto theme.
 */
"auto"
/**
 * 传输操作类型
 */
export type TransferOperation = 
/**
 * 复制操作，保留原文件
 */
"Copy" | 
/**
 * 剪切操作，移动文件并删除原文件
 */
"Cut" | 
/**
 * 缓存根目录迁移
 */
"RootMigration"
/**
 * 传输进度信息
 */
export type TransferProgress = { 
/**
 * 任务ID
 */
task_id: string; 
/**
 * 总文件数
 */
total_files: number; 
/**
 * 已完成文件数
 */
completed_files: number; 
/**
 * 总大小（字节）
 */
total_size: number; 
/**
 * 已传输大小（字节）
 */
transferred_size: number; 
/**
 * 传输速度（字节/秒）
 */
speed: number; 
/**
 * 预计剩余时间（秒）
 */
remaining_time: number; 
/**
 * 当前正在传输的文件
 */
current_file: string; 
/**
 * 任务状态
 */
status: TaskStatus }
/**
 * 传输请求
 */
export type TransferRequest = { 
/**
 * 传输操作类型
 */
operation: TransferOperation; 
/**
 * 源文件路径列表
 */
source_files: string[]; 
/**
 * 目标路径
 */
target_path: string; 
/**
 * 文件名冲突处理策略
 */
conflict_strategy: ConflictStrategy }
/**
 * 传输目标
 */
export type TransferTarget = { 
/**
 * 目标唯一标识符
 */
id: string; 
/**
 * 目标名称
 */
name: string; 
/**
 * 设备类型
 */
device_type: DeviceType; 
/**
 * 目标路径
 */
path: string | null; 
/**
 * 可用空间（字节）
 */
available_space: number | null; 
/**
 * 连接状态
 */
connection_status: ConnectionStatus }
/**
 * 传输任务
 */
export type TransferTask = { 
/**
 * 任务唯一标识符
 */
id: string; 
/**
 * 传输操作类型
 */
operation: TransferOperation; 
/**
 * 源文件路径列表
 */
source_files: string[]; 
/**
 * 传输目标
 */
target: TransferTarget; 
/**
 * 任务状态
 */
status: TaskStatus; 
/**
 * 传输进度
 */
progress: TransferProgress; 
/**
 * 创建时间（Unix时间戳）
 */
created_at: number; 
/**
 * 更新时间（Unix时间戳）
 */
updated_at: number; 
/**
 * 错误消息（如果失败）
 */
error_message: string | null }
export type WindowEffect = 
/**
 * Auto window effect based on platform
 */
"auto" | 
/**
 * Mica effect (Windows 11+)
 */
"mica" | 
/**
 * Acrylic effect (Windows 10+)
 */
"acrylic" | 
/**
 * Sidebar effect (macOS)
 */
"sidebar" | 
/**
 * No window effect
 */
"none"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
